--
NDefines.NAI.PEACE_TERMS_GOLD_BASE_MULT = 0.245
NDefines.NAI.PEACE_TERMS_GIVE_UP_CLAIM = 0
NDefines.NAI.PEACE_TERMS_GIVE_UP_CLAIM_PERMANENT = 0
NDefines.NAI.PEACE_TERMS_CONCEDE_DEFEAT_BASE_MULT = 0.01
NDefines.NAI.PEACE_TERMS_MIN_MONTHS_OF_GOLD = 10
NDefines.NAI.PEACE_TERMS_PILLAGE_CAPITAL_MULT = 0
NDefines.NAI.PEACE_TERMS_TRANSFER_VASSAL_MAX_MULT = 0.5
NDefines.NAI.PEACE_TERMS_ANNUL_TREATIES_BASE_MULT = 0
--
NDefines.NAI.PEACE_TERMS_PROVINCE_OVEREXTENSION_MIN_MULT = 1.0
NDefines.NAI.PEACE_TERMS_PROVINCE_OVEREXTENSION_MAX_MULT = 7.0