NDefines.NMilitary.FLAGSHIP_REQUIRED_NAVY_SIZE_IN_SAILORS = 750	-- 50% reduction
NDefines.NMilitary.BASE_MP_TO_MANPOWER = 0.125					-- 125 men per manpower, halved.
NDefines.NEconomy.LAND_MAINTENANCE_FACTOR = 0.4 				-- 60% more
NDefines.NEconomy.HEAVY_SHIP_MAINT_FACTOR = 0.16 				-- 60% more
NDefines.NEconomy.GALLEY_MAINT_FACTOR = 0.064 					-- 60% more
NDefines.NCountry.REVOLT_SIZE_DEVELOPMENT_MULTIPLIER = 0.07 	-- three quarters
NDefines.NCountry.REVOLT_SIZE_BASE = 3 							-- two thirds
NDefines.NCountry.REVOLT_TECH_IMPACT = 0.02 					-- two thirds
NDefines.NMilitary.SIEGE_FORCE_NEEDED_MULTIPLIER = 2			-- 2/3 base due to smaller numbers
